# Copyright The OpenTelemetry Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

OTEL_PROFILING_ENABLED = "OTEL_PROFILING_ENABLED"
OTEL_PROFILING_EXPORTER = "OTEL_PROFILING_EXPORTER"
OTEL_PROFILING_SAMPLE_INTERVAL = (
    "OTEL_PROFILING_SAMPLE_INTERVAL"
)
OTEL_PROFILING_EXPORT_INTERVAL = (
    "OTEL_PROFILING_EXPORT_INTERVAL"
)
OTEL_PROFILING_MAX_FRAMES = "OTEL_PROFILING_MAX_FRAMES"
OTEL_PROFILING_INCLUDE_TRACE_CONTEXT = (
    "OTEL_PROFILING_INCLUDE_TRACE_CONTEXT"
)
OTEL_PROFILING_EXCEPTION_ENABLED = (
    "OTEL_PROFILING_EXCEPTION_ENABLED"
)
OTEL_PROFILING_EXCEPTION_SAMPLING_INTERVAL = (
    "OTEL_PROFILING_EXCEPTION_SAMPLING_INTERVAL"
)
OTEL_PROFILING_EXCEPTION_COLLECT_MESSAGE = (
    "OTEL_PROFILING_EXCEPTION_COLLECT_MESSAGE"
)
OTEL_PROFILING_LOCK_ENABLED = (
    "OTEL_PROFILING_LOCK_ENABLED"
)
OTEL_PROFILING_MEMORY_ENABLED = (
    "OTEL_PROFILING_MEMORY_ENABLED"
)
OTEL_PROFILING_MEMORY_INTERVAL = (
    "OTEL_PROFILING_MEMORY_INTERVAL"
)
OTEL_PROFILING_MEMORY_TOP_STATS = (
    "OTEL_PROFILING_MEMORY_TOP_STATS"
)
OTEL_PROFILING_MEMORY_IGNORE_PROFILER = (
    "OTEL_PROFILING_MEMORY_IGNORE_PROFILER"
)
OTEL_PROFILING_PPROF_PATH = "OTEL_PROFILING_PPROF_PATH"
OTEL_PROFILING_PPROF_UPLOAD_URL = (
    "OTEL_PROFILING_PPROF_UPLOAD_URL"
)
OTEL_PROFILING_PPROF_HEADERS = (
    "OTEL_PROFILING_PPROF_HEADERS"
)

OTEL_EXPORTER_OTLP_PROFILES_PROTOCOL = (
    "OTEL_EXPORTER_OTLP_PROFILES_PROTOCOL"
)
OTEL_EXPORTER_OTLP_PROFILES_ENDPOINT = (
    "OTEL_EXPORTER_OTLP_PROFILES_ENDPOINT"
)
OTEL_EXPORTER_OTLP_PROFILES_INSECURE = (
    "OTEL_EXPORTER_OTLP_PROFILES_INSECURE"
)
OTEL_EXPORTER_OTLP_PROFILES_HEADERS = (
    "OTEL_EXPORTER_OTLP_PROFILES_HEADERS"
)
OTEL_EXPORTER_OTLP_PROFILES_TIMEOUT = (
    "OTEL_EXPORTER_OTLP_PROFILES_TIMEOUT"
)
OTEL_EXPORTER_OTLP_PROFILES_COMPRESSION = (
    "OTEL_EXPORTER_OTLP_PROFILES_COMPRESSION"
)
OTEL_EXPORTER_OTLP_PROFILES_CERTIFICATE = (
    "OTEL_EXPORTER_OTLP_PROFILES_CERTIFICATE"
)
OTEL_EXPORTER_OTLP_PROFILES_CLIENT_KEY = (
    "OTEL_EXPORTER_OTLP_PROFILES_CLIENT_KEY"
)
OTEL_EXPORTER_OTLP_PROFILES_CLIENT_CERTIFICATE = (
    "OTEL_EXPORTER_OTLP_PROFILES_CLIENT_CERTIFICATE"
)
